### ISSUE TITLE
popup menu needs to always display on screen & center screen mode (like modal)

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1845] opened 2016-07-25 19:42 UTC
we need to change the popup menu so that it can detect where to position itself as to always display on screen (also should have a mode where its always center screen like a modal)

**Comment by mlzummo** [comment] 2016-07-29 02:38
This can be done via css but might want a PP with css

**Comment by GordonSmith** [comment] 2016-07-30 05:25
Duplicate of https://github.com/hpcc-systems/Visualization/issues/1685

**Closed by GordonSmith** 2016-07-30 05:25 UTC
Labels: enhancement
