### ISSUE TITLE
Filter issue with two tables and Roxie Services

### ISSUE THREAD

**Issue by hamiltwp** [hpcc-systems/Visualization#1791] opened 2016-07-06 18:48 UTC
reference DSP issue "Inconsistent behavior of Filter in View #1551"
https://github.com/hpcc-systems/DSP/issues/1551

The carrot filter behaves inconsistently when there are two widgets based on the same Thor table with deploy Roxie services checked.

1, Build a dashboard with two tables, both with datasource demo::salesdata
2. First table using fields AVE(revenue), distribution_channel , salesorganisation, and filter on salesorganisation = "Australia"
3. Second table on fields AVE(quality), salesorganisation with no filter
4. Edit, Settings and check Deploy as Roxie Services
5. Run, and alter filter from the carrot menu with clear and submit, repeatedly.

Sometimes the result will be empty, and sometimes will have the unfiltered result

**Comment by GordonSmith** [comment] 2016-07-30 05:12
Duplicate of:  https://github.com/hpcc-systems/Visualization/issues/1871

**Closed by GordonSmith** 2016-07-30 05:12 UTC
Labels: duplicate
