### ISSUE TITLE
Tabular widgets auto scroll left after sort

### ISSUE THREAD

**Issue by senthilkumarperiasamy** [hpcc-systems/Visualization#2463] opened 2018-04-10 14:39 UTC
See Jira ticket https://jira.rsi.lexisnexis.com/browse/RAMPS-534 for more information

**Comment by GordonSmith** [comment] 2018-06-08 13:32
Duplicate of:  https://github.com/hpcc-systems/Visualization/issues/2615

**Closed by GordonSmith** 2018-06-08 13:32 UTC
Labels: duplicate
