### ISSUE TITLE
surfacePadding current value not present in Layout Designer

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1979] opened 2016-09-01 20:47 UTC
https://github.com/hpcc-systems/DSP/issues/1028

cross reference to above issue

**Comment by GordonSmith** [comment] 2016-09-05 09:23
Duplicate of https://github.com/hpcc-systems/Visualization/issues/1981

**Closed** 2016-09-05 09:23 UTC
Labels: duplicate
