### ISSUE TITLE
Global Filter not applied to second widget

### ISSUE THREAD

**Issue by hamiltwp** [hpcc-systems/Visualization#1926] opened 2016-08-12 15:41 UTC
In v1.14.x when there are two widgets in the dashboard, the global filter does not apply to the second widget.

**Comment by GordonSmith** [comment] 2016-08-12 15:50
I am pretty sure this is a duplicate of:  https://github.com/hpcc-systems/Visualization/issues/1918

**Comment by GordonSmith** [comment] 2017-08-04 08:16
Closed "timed-out", please reopen if needed.

**Closed by GordonSmith** 2017-08-04 08:16 UTC
Labels: duplicate
