### ISSUE TITLE
HTML_Marshaller doesnt have designmode PP

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#839] opened 2015-09-01 19:28 UTC
due to it extending Layout/Tabbed instead of Grid as opposed to before 1.6

**Comment by GordonSmith** [comment] 2015-09-01 20:52
Closing as duplicate of https://github.com/hpcc-systems/Visualization/issues/817

**Closed by GordonSmith** 2015-09-01 20:52 UTC
