### ISSUE TITLE
Global filter does not apply default filter value

### ISSUE THREAD

**Issue by hamiltwp** [hpcc-systems/Visualization#1928] opened 2016-08-12 15:46 UTC
In a version 1.14.x dashboard the filter is not applied by default, when the widget is first viewed.

**Comment by GordonSmith** [comment] 2016-08-12 15:50
I am pretty sure this is a duplicate of:  https://github.com/hpcc-systems/Visualization/issues/1918

**Comment by GordonSmith** [comment] 2016-08-15 12:22
Closing as duplicate

**Closed by GordonSmith** 2016-08-15 12:22 UTC
Labels: duplicate
