### ISSUE TITLE
Distinctive hover text not displayed for measures of stacked chart

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#1750] opened 2016-06-14 14:06 UTC
Hover over the of the stacks

Issue: The hover text for mark1 is displayed on hovering over mark1, mark2 and mark3.
(The hover text is not distinctive for mark2 and mark3.)

see for details: https://github.com/hpcc-systems/DSP/issues/1392

**Comment by GordonSmith** [comment] 2016-06-14 14:12
Duplicate of:  https://github.com/hpcc-systems/Visualization/issues/1537 @mlzummo any updates?

**Closed** 2016-06-14 14:13 UTC
Labels: duplicate
